version: '3'
services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.2.0
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db